apiVersion: v1
appVersion: "1.0"
description: A Helm chart edmonds Community College
name: portagebay-ecc-platform-ui
version: 0.1.0
keywords:
  - Edmonds
  - frontend
maintainers:
  - name: Xandon
    email: xandon@hotmail.com
    url: https://github.com/Xandon/portagebay-ecc-platform-ui