# Default values for portagebay-ecc-platform-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: us.gcr.io/edmonds-community-college
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}

scaler:
  enabled: true
  max: 20
  min: 2
  targetAverageUtilization:
    cpu: 80
    memory: 80

env:
  - name: production
    value: "true"

service:
  enabled: true
  type: NodePort
  port: 80
  targetPort: http
  healthPath: /healthz

ingress:
  enabled: false
  staticIP: k8-ingress